In [5]:
import numpy as np

In [6]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [7]:
my_arr, 

(array([     0,      1,      2, ..., 999997, 999998, 999999]),)

In [8]:
%timeit my_arr2 = my_arr * 2

1.65 ms ± 169 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
%timeit my_list2 = [x * 2 for x in my_list]

52.5 ms ± 3.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
data = np.array([[1.5, -0.1, 6], [4, 0, -8.5]]) # n-dimensional array

In [11]:
data

array([[ 1.5, -0.1,  6. ],
       [ 4. ,  0. , -8.5]])

In [12]:
# performing mathematical operations
data * 10
data - 1
data - 1 * 10
data + data

array([[  3. ,  -0.2,  12. ],
       [  8. ,   0. , -17. ]])

In [13]:
array2 = np.array([['a', 1, 2], [4,5,6]])

In [14]:
array2
array2.dtype

dtype('<U21')

In [15]:
data.shape #rows, cols

(2, 3)

In [16]:
data.dtype

dtype('float64')

In [17]:
np.zeros(5)
# ==
np.array(np.zeros(5))
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.empty((4,3, 2))
# np.empty((2,3), dtype=float,order='C')

array([[[4.68111526e-310, 0.00000000e+000],
        [0.00000000e+000, 1.13832725e-320],
        [6.12641401e-322, 0.00000000e+000]],

       [[1.13832725e-320, 1.06099790e-313],
        [0.00000000e+000, 1.13832725e-320],
        [6.12641401e-322, 0.00000000e+000]],

       [[1.13980944e-320, 1.27319748e-313],
        [0.00000000e+000, 1.13980944e-320],
        [1.48539706e-313, 0.00000000e+000]],

       [[1.13980944e-320, 6.12641401e-322],
        [0.00000000e+000, 1.13980944e-320],
        [1.06099790e-313, 0.00000000e+000]]])

In [19]:
type(np.dtype) #dtype is an obj that contains data about the data (medtadata)

numpy._DTypeMeta

In [20]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)

In [21]:
arr1.dtype, arr2

(dtype('float64'), array([1, 2, 3], dtype=int32))

In [22]:
# changing datatype
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [23]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [24]:
float_arr.astype(np.int64)

array([1, 2, 3, 4, 5])

In [25]:
numeric_strings = np.array(["1","2"])
numeric_strings.astype(np.float32) #note that np.float32 and float are different
float_arr.astype(np.string_)

array([b'1.0', b'2.0', b'3.0', b'4.0', b'5.0'], dtype='|S32')

In [26]:
# as type will always create a new copy of the array
# pg:109

In [27]:
import numpy as np
arr = np.array([[1., 2., 3.], [4.,5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [29]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
arr 


array([[1., 2., 3.],
       [4., 5., 6.]])

In [31]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [32]:
arr2 = np.array([[0., 4., 1.], [7., 3., 6.]])
arr2

array([[0., 4., 1.],
       [7., 3., 6.]])

In [33]:
arr2 > arr

array([[False,  True, False],
       [ True, False, False]])

In [34]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr[5]

5

In [36]:
arr[5:8]

array([5, 6, 7])

In [37]:
arr[5:18] = 696969

In [38]:
arr

array([     0,      1,      2,      3,      4, 696969, 696969, 696969,
       696969, 696969])

In [39]:
arr_slice = arr[5:8]

In [40]:
arr

array([     0,      1,      2,      3,      4, 696969, 696969, 696969,
       696969, 696969])

In [41]:
arr_slice

array([696969, 696969, 696969])

In [42]:
arr_slice[1] = 172398712 

In [43]:
arr_slice

array([   696969, 172398712,    696969])

In [44]:
arr

array([        0,         1,         2,         3,         4,    696969,
       172398712,    696969,    696969,    696969])

In [45]:
arr[:] = 23456789
arr

array([23456789, 23456789, 23456789, 23456789, 23456789, 23456789,
       23456789, 23456789, 23456789, 23456789])

In [46]:
new_arr = arr[5:8].copy()
new_arr

array([23456789, 23456789, 23456789])

In [47]:
new_arr[:] = 0
new_arr, arr

(array([0, 0, 0]),
 array([23456789, 23456789, 23456789, 23456789, 23456789, 23456789,
        23456789, 23456789, 23456789, 23456789]))

In [48]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d[2], arr2d[0][2]
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d, arr3d.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 (2, 2, 3))

In [50]:
arr3d[0], arr3d[0][0][0]

(array([[1, 2, 3],
        [4, 5, 6]]),
 1)

In [51]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] =old_values
arr3d, old_values

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [52]:
arr3d[1, 0]

array([7, 8, 9])

In [53]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr2d[:2, :1]
lower_dim_slice = arr2d[1, :2]
lower_dim_slice #1dim

array([4, 5])

In [56]:
lower_dim_slice.shape #here 2 represents the number of elements in the first dimension, since thae arr has only one dimension

(2,)

In [57]:
arr2d[:2, 2].shape #2,

(2,)

In [58]:
arr2d[:, :1], arr2d[:, 0], arr2d[:, :1].shape, arr2d[:, 0].shape
# colon means take the entire axis

(array([[1],
        [4],
        [7]]),
 array([1, 4, 7]),
 (3, 1),
 (3,))

In [59]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])


In [60]:
arr2[:2, 1:]

array([[4., 1.],
       [3., 6.]])

In [61]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

arr2d[:1, :1], arr2d[0, :1]

(array([[1]]), array([1]))

In [62]:
names = np.array

In [63]:
arr2d[2, :1]

array([7])

In [64]:
arr2d[2:, :] # [[7,8,9]]
arr2d[1:2, :2] # [[4,5]]

array([[4, 5]])

In [65]:
 names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [66]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
 [-12, -4], [3, 4]])
names, data

(array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4'),
 array([[  4,   7],
        [  0,   2],
        [ -5,   6],
        [  0,   0],
        [  1,   2],
        [-12,  -4],
        [  3,   4]]))

In [67]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [72]:
data[names == 'Bob', 1:]

array([[7],
       [0]])

In [74]:
data[names == 'Bob', 1]

array([7, 0])

In [75]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [78]:
~(names == 'Bob') #~ inverts a boolean array

array([False,  True,  True, False,  True,  True,  True])

In [79]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [80]:
cond = names == "Bob"