In [1]:
import numpy as np

In [2]:
# Fancy indexing

In [3]:
arr = np.zeros((8,4))

In [4]:
for i  in range(8):
    arr[i] = i

In [5]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [6]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [7]:
arr[[-3, -4, -7]]

array([[5., 5., 5., 5.],
       [4., 4., 4., 4.],
       [1., 1., 1., 1.]])

In [8]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [9]:
arr[[0,1,2,3], [0,3,2,1]]

array([ 0,  7, 10, 13])

In [10]:
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [11]:
arr[[0,1,2,3], [0,3,2,1]] = 79898

In [12]:
arr

array([[79898,     1,     2,     3],
       [    4,     5,     6, 79898],
       [    8,     9, 79898,    11],
       [   12, 79898,    14,    15],
       [   16,    17,    18,    19],
       [   20,    21,    22,    23],
       [   24,    25,    26,    27],
       [   28,    29,    30,    31]])

In [13]:
arr.T


array([[79898,     4,     8,    12,    16,    20,    24,    28],
       [    1,     5,     9, 79898,    17,    21,    25,    29],
       [    2,     6, 79898,    14,    18,    22,    26,    30],
       [    3, 79898,    11,    15,    19,    23,    27,    31]])

In [16]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1
]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [17]:
np.dot(arr.T, arr) #dot product of vectors

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [18]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [19]:
arr.swapaxes(0,1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [21]:
arr.T, arr

(array([[ 0,  1,  6, -1,  1],
        [ 1,  2,  3,  0,  0],
        [ 0, -2,  2, -1,  1]]),
 array([[ 0,  1,  0],
        [ 1,  2, -2],
        [ 6,  3,  2],
        [-1,  0, -1],
        [ 1,  0,  1]]))

In [ ]:
# Pseudorandom number generation

In [23]:
samples = np.random.standard_normal(size=(4,4))
samples

array([[-0.59637838,  1.18167255, -0.22725908, -2.28231358],
       [ 1.79907904,  0.91432653, -1.48363219, -2.14157329],
       [ 0.6619276 , -1.0391083 ,  0.2496552 ,  0.20080426],
       [ 0.01667779,  0.27188537, -0.10677684,  1.09796236]])

In [24]:
from random import normalvariate
N = 1_000_000
%timeit samples = [normalvariate(0,1) for _ in range(N)]

551 ms ± 17.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [25]:
%timeit np.random.standard_normal(N)

20.8 ms ± 156 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [26]:
rng = np.random.default_rng(seed = 12345)
data = rng.standard_normal((2,3))

In [27]:
rng, data

(Generator(PCG64) at 0x7FA72037E7A0,
 array([[-1.42382504,  1.26372846, -0.87066174],
        [-0.25917323, -0.07534331, -0.74088465]]))

In [30]:
abc = np.random.default_rng(seed = 12345)
abc.standard_normal((2,5))
# we use the rng generator with certain seed value such that the "random" values it generates is same everytime

array([[-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331],
       [-0.74088465, -1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306]])

In [31]:
# universal functions element wise operations or scalar wise operations
arr = np.arange(10)
arr, np.sqrt(arr), np.exp(arr)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]),
 array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03]))

In [32]:
np.array(8)

array(8)

In [58]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)
x, y
np.maximum(x, y)

array([0.7364691 , 0.68618251, 1.21500461, 0.21605944, 1.58453379,
       0.28224121, 0.90954639, 0.39507157])

In [61]:
arr = rng.standard_normal(8) * 10
remainder, whole_part = np.modf(arr)
arr, remainder, whole_part

(array([-10.30665854,   2.99218328,  -8.46239971,   1.966203  ,
         -8.99637825,  -2.56605429,  16.72547766,  -3.75269646]),
 array([-0.30665854,  0.99218328, -0.46239971,  0.966203  , -0.99637825,
        -0.56605429,  0.72547766, -0.75269646]),
 array([-10.,   2.,  -8.,   1.,  -8.,  -2.,  16.,  -3.]))

In [64]:
out = np.zeros_like(arr)
np.add(arr, 1)

array([-9.30665854,  3.99218328, -7.46239971,  2.966203  , -7.99637825,
       -1.56605429, 17.72547766, -2.75269646])

In [65]:
np.add(arr, 1, out= out)

array([-9.30665854,  3.99218328, -7.46239971,  2.966203  , -7.99637825,
       -1.56605429, 17.72547766, -2.75269646])

In [66]:
out

array([-9.30665854,  3.99218328, -7.46239971,  2.966203  , -7.99637825,
       -1.56605429, 17.72547766, -2.75269646])

In [74]:
np.add(arr,1, out=out)
arr, out

(array([-10.30665854,   2.99218328,  -8.46239971,   1.966203  ,
         -8.99637825,  -2.56605429,  16.72547766,  -3.75269646]),
 array([-9.30665854,  3.99218328, -7.46239971,  2.966203  , -7.99637825,
        -1.56605429, 17.72547766, -2.75269646]))

In [ ]:
#array oriendted programming with arrays

In [78]:
points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points, points)
ys, xs

(array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
        [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
        [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
        ...,
        [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
        [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
        [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]]),
 array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        ...,
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]]))

In [ ]:
z = np.sqrt(xs ** 2 + ys ** 2)
z